server:
  port: 80
#  tomcat:
#    max-threads: 1000
#  servlet:
#    context-path: /

#datasource
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/jtsys?serverTimezone=GMT%2B8&characterEncoding=utf-8&useUnicode=true
    username: root
    password: root

#  mvc:
#    servlet:
#      path: /api

mybatis:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/sys/*Mapper.xml
  
logging:
  level:
    com.qianxia:  DEBUG

#management:#  endpoints:#    web:#      exposure:#        include:  "*"
